### ISSUE TITLE
EMS codes look up

### ISSUE THREAD

**Issue by joethorley** [bcgov/wqg_data#15]
The EMS codes in the all_wqgs.csv file are congruent with the codes listed in the “EMS Parameter Dictionary” available on DataBC: https://catalogue.data.gov.bc.ca/dataset/bc-environmental-monitoring-system-results/resource/5c982e1a-7c04-466a-a0d7-a775f7968a7a
 
There are still some missing EMS codes.  We will need to work with ENV staff to get these codes entered into the EMS system.

**Comment by HeatherGranger** [comment]
@atillmanns is looking into filling some of these, but at this point if there's no codes then we won't be able to compare a guideline to it.

**Comment by joethorley** [comment]
Created separate issues #27 and #28 with remaining codes
