### ISSUE TITLE
Why multiple EMS Parameters or Taxonomic Code for a substance?

### ISSUE THREAD

**Issue by joethorley** [bcgov/wqg_data#2]
May need to add two columns (if Taxonomic Code separate) or have lookup table?

**Comment by atillmanns** [comment]
In the EMS database there are often multiple codes for one parameter due to different sampling and/or laboratory methods.  For the WQGs, we don’t specify the sampling or analytical methods so data collected with any method is acceptable.  Therefore, more than one code is needed.  As for the multiple codes listed in the logical conditions column for hardness, this is to denote that a user may use dissolved or total hardness.

The only Taxonomic code is for cyanobacteria (CYANOB).  All other codes are parameter codes.

**Comment by joethorley** [comment]
Is there an EMS code we can use for CYANOB instead?

**Comment by joethorley** [comment]
To deal with the multiple EMS codes I think we should include the most common one in EMS_Code and then have a second spreadsheet that has EMS_Code and Equivalent_EMS_Code where we indicate for the most common EMS_Codes what the equivalent EMS codes are row by row ie just one entry for Equivalent on each row.

If you could just scan through the data and make sure the most common EMS code is first in the commas we can quickly generate.

**Comment by HeatherGranger** [comment]
Reviewing the guideline, the Parameter should be written as 'Cyanobacterial Toxins: Total Cyanobacteria'. Therefore the EMS code would be 'MCYS' as the other Cyanobacterial parameters. This removes the issue of the taxonomic code. 

This now creates 2 guidelines (Cyanobacterial Toxins: Total Cyanobacteria and Cyanobacterial Toxins: Microcystins Total) for Recreation-swimming with the same EMS code (MCYS). Will this affect how the guideline is pulled onto a plot? aka will there be 2 guidelines on a plot?

The guideline is presented in two ways as the user may have measured in either cells/mL for cyanobacteria or mg/L for microcystins.

**Comment by HeatherGranger** [comment]
For dealing with the multiple codes, what you're suggesting is possible, but that would require us to make a rule to use the most current code (which would exclude historic data using an older EMS parameter code from guideline comparison) and then there's the issue of not bringing in the total or dissolved anions if we specify one code. Is there a way to do a look up table for a few parameters that have multiple codes? What do you think @atillmanns

**Comment by joethorley** [comment]
@HeatherGranger - We don't think the Cyanobacterial cell and the toxins they produces should have the same EMS code as they are different things which are measured in different ways.

**Comment by joethorley** [comment]
@HeatherGranger - we were suggesting a lookup table but to avoid having multiple tables we could duplicate rows in the wqgs spreadsheet that have more than one ems code.

**Comment by HeatherGranger** [comment]
@joethorley - let's leave the EMS parameter code blank for cyanobacterial toxins: total cyanobacteria. I don't think not being able to generate a guideline for this parameter is an issue. The EMS code MCYS fits best with cyanobacterial toxins: total microcystins.

**Comment by HeatherGranger** [comment]
Duplicating rows makes sense. Would there be a difference in how the EMS codes are EMS equivalent codes are used?

**Comment by joethorley** [comment]
@HeatherGranger - We'll duplicate - I'm not sure what you mean by

>  Would there be a difference in how the EMS codes are EMS equivalent codes are used?

**Comment by HeatherGranger** [comment]
We can clarify tomorrow, but I just mean in how the app uses the common codes vs the equivalent codes. For example, will the app bring in all of the data under the multiple EMS parameter codes to compare the guideline to.

**Comment by joethorley** [comment]
@HeatherGranger - Yes we can ensure that from a users perspective they are treated equally

**Comment by atillmanns** [comment]
Not sure the idea of two spreadsheets works that great from the perspective of having the data on DataBC.

**Comment by joethorley** [comment]
done
