### ISSUE TITLE
Try and move notes into coding and remove

### ISSUE THREAD

**Issue by joethorley** [bcgov/wqg_data#25]

**Comment by atillmanns** [comment]
@joethorley perhaps a conversation about the notes would be useful?

**Comment by joethorley** [comment]
@atillmanns - I agree but I think we should deal with the most common ones as we are doing with the issues and then discuss the remaining ones.

**Comment by joethorley** [comment]
@atillmanns - I'm ready to discuss the notes whenever you are

**Comment by joethorley** [comment]
see #41

**Comment by joethorley** [comment]
being dealt with
