### ISSUE TITLE
Commit not merged?

### ISSUE THREAD

**Issue by atillmanns** [bcgov/wqg_data#26]
@joethorley - I pushed the wqgs_all.csv file with the added EMS codes but there is something about merging with main branch?  Is there something else I have to do to merge in the changes?  Thanks!

**Comment by joethorley** [comment]
@atillmanns Can you provide a screenshot of the message?

**Comment by atillmanns** [comment]
It looks like my changes are in the file now.  Still learning how GitHub works.  Thanks for your patience @joethorley
