### ISSUE TITLE
Variables with unrecognized EMS Codes

### ISSUE THREAD

**Issue by joethorley** [bcgov/wqg_data#28]
I think the following have been mangled by Excel - can we fix by just adding leading 0s so they are 4 characters in length (after the EMS_)?

```r
# A tibble: 18 x 2
   Variable                                    EMS_Code
   <chr>                                       <chr>   
 1 Coliforms Fecal                             EMS_450 
 2 Colour Apparent                             EMS_1   
 3 Colour True                                 EMS_2   
 4 Cyanide Weak Acid Dissociable               EMS_157 
 5 Cyanobacterial Toxins: MicrocystinLR        EMS_MCYS
 6 Cyanobacterial Toxins: Microcystins Total   EMS_MCYS
 7 Enterococci                                 EMS_148 
 8 Escherichia coli                            EMS_147 
 9 Ethylbenzene                                EMS_B023
10 Ethylbenzene                                EMS_B024
11 Organic Carbon Total                        EMS_103 
12 Phenols Total                               EMS_117 
13 Resin acids Total                           EMS_128 
14 Salinity                                    EMS_130 
15 Sulfolane                                   EMS_SULF
16 Sulphate Total                              EMS_121 
17 Sulphide Total                              EMS_125 
18 Total dissolved solids (filterable residue) EMS_7 
```

**Comment by joethorley** [comment]
Note these are based on current EMS codes in wqbc

**Comment by joethorley** [comment]
Confirmed same with latest from ems

**Comment by joethorley** [comment]
I can confirm after filling in missing leading 0s that the only unrecognized EMS codes are 
```r
# A tibble: 5 x 2
  Variable                                  EMS_Code
  <chr>                                     <chr>   
1 Cyanobacterial Toxins: MicrocystinLR      EMS_MCYS
2 Cyanobacterial Toxins: Microcystins Total EMS_MCYS
3 Ethylbenzene                              EMS_B023
4 Ethylbenzene                              EMS_B024
5 Sulfolane                                 EMS_SULF
```

**Comment by HeatherGranger** [comment]
Ethylenzene EMS_B021
I'm assuming you figured out the three leading 0's preceding total dissolved solids, color apparent and color true. 
I'm waiting on a response on the MCYS and SULF.

**Comment by HeatherGranger** [comment]
It's confirmed that SULF and MCYS are EMS parameter codes present in EMS, however they have not been updated in the parameter dictionary.

**Comment by joethorley** [comment]
Just to confirm - should Ethylbenzene be EMS_B021?

**Comment by joethorley** [comment]
With regard SULF and MCYS - we'll have to leave them blank until the dictionary is updated because we need all the variables to to cross-reference with information in rems and wqbc.

**Comment by HeatherGranger** [comment]
yes ethylbenzene should be EMS_B021.
ok, leave SULF and MCYS blank and I'll ask to have the dictionary updated. thanks!

**Comment by HeatherGranger** [comment]
One more note on this - the EMS application manager is looking into having an automatically updated parameter dictionary .csv which references exactly what parameters are in EMS. So at this point the parameter dictionary will be out of sync with EMS until its manually updated. SULF and MCYS are in EMS but not in the parameter dictionary...for now.

**Comment by joethorley** [comment]
Good to know
