### ISSUE TITLE
What does `Lower SWQG` mean in the notes?

### ISSUE THREAD

**Issue by joethorley** [bcgov/wqg_data#30]

**Comment by atillmanns** [comment]
Lower WSQG – a concentration that will protect aquatic life from the adverse effects of a toxic
substance in most situations (equivalent to CCME’s Threshold Effect Level or Interim Sediment
Quality Guidelines (TEL or ISQGs; CCME 2001))

**Comment by joethorley** [comment]
Ah so maybe we need this as type Threshold in the Level column suggested in #33?

**Comment by joethorley** [comment]
@atillmanns - can you confirm that we no longer need this since all the information is in the PredictedEffectLevel as "No Effect" or should it be "Probable Effect" or its own category?

**Comment by joethorley** [comment]
Confirmed by issue #31
