### ISSUE TITLE
What does `Upper SWQG` mean in the notes?

### ISSUE THREAD

**Issue by joethorley** [bcgov/wqg_data#31]
Also see #30

**Comment by atillmanns** [comment]
• Upper WSQGs – a concentration that if exceeded will likely cause severe effects on aquatic life
(equivalent to CCME’s Probable Effect Level (PEL; CCME (2001)).

**Comment by joethorley** [comment]
So does it make most sense to add this the Level column as Protective as suggested in issue #33?

**Comment by joethorley** [comment]
@atillmanns - can you confirm that we can code this as "Probable Effect"  in the PredictedEffectLevel column and remove from the notes.

**Comment by atillmanns** [comment]
@joethorley - 
Interim sediment quality guideline level = no effect
Lower SWQG = no effect
Probable Effect Level = probable effect
Upper SWQG = probable effect
