### ISSUE TITLE
What does `Interim Sediment Quality Guideline` mean in the notes?

### ISSUE THREAD

**Issue by joethorley** [bcgov/wqg_data#32]
And why are they all type `Working` not `Interim`?

**Comment by atillmanns** [comment]
"Interim" guidelines are created when there is not enough data to generate a full guideline.  You will see in the "Type" column that sometimes B.C. guidelines are listed as interim.  Guidelines adopted from another jurisdiction are listed as "working" under the Type column.  The fact that they are still interim guidelines are given in the notes.  This is information for the user to consider when applying the guideline.

**Comment by joethorley** [comment]
I'm thinking it makes more sense to have the Type as Interim (since the data is for BC) and to move the fact they are working in another jurisdiction into the notes - thoughts?

**Comment by atillmanns** [comment]
We have policy documents that describe the different types of guidelines - for B.C. there is approved, working (adopted from another jurisdiction) or interim.  Interim guidelines derived in B.C. and approved on an interim basis.  We need to be consistent with the policy documents.

**Comment by joethorley** [comment]
@atillmanns - gotcha - since `Interim Sediment Quality Guideline` is almost fully captured by the fact that all entries are Media = Sediment and Type = Working can we remove from notes?

**Comment by atillmanns** [comment]
@joethorley - yes, we can remove the phrase, "interim sediment quality guideline" from the notes.
