### ISSUE TITLE
What does `Probable Effect Level` mean in the notes?

### ISSUE THREAD

**Issue by joethorley** [bcgov/wqg_data#33]

**Comment by atillmanns** [comment]
This is the concentration that is likely to cause an effect.  It is not a protective concentration but helpful to managers to gauge the level of impact.

**Comment by joethorley** [comment]
In which case it may make sense to add a column called  something like Level which has two values with names like Protective (most things) and Effective -thoughts?

**Comment by joethorley** [comment]
dealt with by issue #36
