### ISSUE TITLE
In the notes where it says `Minimum 5 samples` I'm assuming short term ie 1 day

### ISSUE THREAD

**Issue by joethorley** [bcgov/wqg_data#34]
Can you confirm?

**Comment by atillmanns** [comment]
@HeatherGranger  - the question is for the recreation guidelines for Enterococci and Escherichia coli

**Comment by HeatherGranger** [comment]
The recreation guidelines for both Enterococci and E.coli which specific minimum 5 samples are calculated as geomeans, so it's 5 samples in 30 days.

**Comment by joethorley** [comment]
dealt with by issue #35
