### ISSUE TITLE
Diethyl phthalate duplicate

### ISSUE THREAD

**Issue by sebdalgarno** [bcgov/wqg_data#43]
Two rows of Diethyl phthalate with all columns identical except for Limit
This confirmed in the raw spreadsheet originally sent by @atillmanns so is not a result of subsequent changes.
Which Limit is correct?

**Comment by sebdalgarno** [comment]
Narrative Condition is "Sediment with 1% Organic Carbon" for both

**Comment by sebdalgarno** [comment]
@atillmanns or @HeatherGranger I think someone from your team will have to resolve this one

**Comment by sebdalgarno** [comment]
when you do resolve, please just post the solution here, and I'll change in the repository so we avoid git conflict - thanks!

**Comment by HeatherGranger** [comment]
@sebdalgarno Limit 0.61 is the Lower Limit. Limit 1.10 is the Upper Limit.

**Comment by sebdalgarno** [comment]
OK thanks @HeatherGranger  will make that change

**Comment by sebdalgarno** [comment]
done
