### ISSUE TITLE
Chlorophenol, PCP - Drinking Water duplicate

### ISSUE THREAD

**Issue by sebdalgarno** [bcgov/wqg_data#44]
in current all_wqgs data, all columns are identical for Chlorophenol, PCP - Drinking Water except Limit.

In original spreadsheet, the differ in Type (Aesthetic and Maximum) - somehow both now have type of Aesthetic Objective

Row with Limit = 0.06 should have Type 'Maximum'

**Comment by HeatherGranger** [comment]
@sebdalgarno fixed in the latest commit

**Comment by sebdalgarno** [comment]
thanks @HeatherGranger !
