### ISSUE TITLE
Ammonia Total - Long Term Chronic duplicates

### ISSUE THREAD

**Issue by sebdalgarno** [bcgov/wqg_data#45]
There are two sets of duplicates for Ammonia Total - Long Term Chronic
1. Condition = '0<= EMS_0013 & EMS_0013 < 15 & 6.5 <= EMS_0004 & EMS_0004 < 7.7'
2. Condition = '0<= EMS_0013 & EMS_0013 < 15 & 7.7 <= EMS_0004 & EMS_0004 < 8'

Everything including Condition is identical but two possible Limits

This is confirmed in the original spreadsheet, so is not a result of subsequent changes

**Comment by sebdalgarno** [comment]
@atillmanns or @HeatherGranger I think someone from your team will have to resolve this one

**Comment by sebdalgarno** [comment]
when you do resolve, please just post the solution here, and I'll change in the repository so we avoid git conflict - thanks!

**Comment by HeatherGranger** [comment]
Thanks @sebdalgarno . I'll leave these aquatic life guideline issues with the conditions for @atillmanns  to flush out - she's the expert on those. She'll be back Monday.

**Comment by atillmanns** [comment]
Hi @sebdalgarno - the problem is with the temperature condition.  Can I make the change directly to the spreadsheet?  Let me know when a good time is and I will pull the newest version, make the change and push it back up.

**Comment by sebdalgarno** [comment]
hi @atillmanns you can make the change any time this afternoon - I won't be working on the repository.
Thanks!

**Comment by atillmanns** [comment]
thanks for noticing this error @sebdalgarno !  All fixed and pushed back up.

**Comment by sebdalgarno** [comment]
great thanks @atillmanns !
