### ISSUE TITLE
Strip Total and Dissolved into new column

### ISSUE THREAD

**Issue by sebdalgarno** [bcgov/wqg_data#50]
if doesn't say explicitly, assume 'Total'...
what should the new column name be?

**Comment by joethorley** [comment]
I don't think we should strip the columns into Total and Dissolved because it doesn't apply in all situations.

**Comment by sebdalgarno** [comment]
FYI the initial comment from Angeline - 

Some substances (aluminum, cadmium, copper, iron, organic carbon and sulphate) have both dissolved and total forms.  We think it may be confusing for the user as they won't know for example, that the guideline for dissolved sulphate is only for livestock and may assume that there are no other guidelines for sulphate.  I suggest that we strip off the "total" and "dissolved" labels from the substance and put this in a separate column.  If the substance has no label, then we can assume it is total.  Within the table then, it will need to be specified if the WQG value is for total or dissolved.

**Comment by joethorley** [comment]
I think this only works if everything that is not Total or Dissolved can be labelled Total.

**Comment by sebdalgarno** [comment]
done
