### ISSUE TITLE
Cases with open-ended Conditions

### ISSUE THREAD

**Issue by sebdalgarno** [bcgov/wqg_data#51]
These need to be added to limits spreadsheet

From @atillmanns review of app:

"The second glitch is for substances with logical conditions and it can be traced back to the "all_wqgs.csv" sheet.  It seems we are missing maximum values for some of the parameters.  For example, for Alkalinity, when calcium dissolved is >8 mg/L then no guideline shows up.  However, the user needs to know that for water bodies with dissolved calcium >8 mg/L, the guideline is actually >20 mg/L.  This doesn't fit so well into our table structure.  I'll pull all the data together and then we can see how best to integrate this with the "all_wqgs.csv" spreadsheet."

**Comment by atillmanns** [comment]
New limit rows have been added.
