### ISSUE TITLE
Type vs. Days/Samples

### ISSUE THREAD

**Issue by sebdalgarno** [bcgov/wqg_data#52]
This relates to: https://github.com/poissonconsulting/shinywqg/issues/22

We need to organize Type vs. Days/Samples better. Here are all the unique combinations of these so far:

<img width="448" alt="Screen Shot 2020-03-03 at 2 06 21 PM" src="https://user-images.githubusercontent.com/15878432/75824492-72a2d280-5d58-11ea-8828-72b107ca942b.png">

See for example cases where Long term chronic have Days/Samples of 1 - this seems wrong. 
Also cases where Type is Primary Contact but can have different Days/Samples. 

I think we need to create a new column that defines the Time (Short term vs. long term) and a column that defines the Type - I feel that the current Type column is mixing these things,

**Comment by atillmanns** [comment]
Row row #1 and #2 above, this first is for aquatic life samples in water and the second is for aquatic life samples in sediment.  This is not a mistake but recognizes the temporal variability substances in water.  For rows #4-#9, @HeatherGranger  - do you have any comment on these?

**Comment by HeatherGranger** [comment]
#4-9 are correct. Maximum acceptable concentrations and aesthetic objectives are drinking water guidelines. Primary contact is recreation guidelines. Both uses have mean and single max sample guidelines. 
I think it looks confusing because the aquatic life guidelines for Type include a time frame, whereas the drinking water and recreation Type do not. I think it may get more confusing as we're going to start adding more titles to define a column in this spreadsheet. 
Alternatively, if it makes more sense to add a time frame column, I could come up with something for the drinking water and recreation guidelines. It would not be long term or short term though.

**Comment by sebdalgarno** [comment]
I think we can simply leave as it is if you think that's best - my main concern was related to the Statistic issue #68 and whether changing Type as it relates to Days/Samples might resolve that. But now that we've resolved that issue I think we can leave this one alone - Joe any thoughts?

**Comment by joethorley** [comment]
These are all the combinations we have when considered Use, Type, Days, Samples and Statistic

```r
# A tibble: 30 x 5
   Use                           Type                                 Days Samples Statistic 
   <chr>                         <chr>                               <dbl>   <dbl> <chr>     
 1 Agriculture - Livestock       Long-term chronic                      30       5 mean      
 2 Aquatic Life - Freshwater     Long-term chronic                      30       5 mean      
 3 Aquatic Life - Marine         Long-term chronic                       1       1 max       
 4 Aquatic Life - Marine         Long-term chronic                      30       5 mean      
 5 Aquatic Life - Freshwater     Long-term chronic                       1       1 max       
 6 Aquatic Life - Freshwater     Short-term acute                        1       1 max       
 7 Agriculture - Irrigation      Long-term chronic                      30       5 mean      
 8 Agriculture - Irrigation      Short-term acute                        1       1 max       
 9 Agriculture - Livestock       Short-term acute                        1       1 max       
10 Drinking Water                Maximum Acceptable Concentration        1       1 max       
11 Wildlife                      Short-term acute                        1       1 max       
12 Aquatic Life - Marine         Short-term acute                        1       1 max       
13 Wildlife                      Long-term chronic                      30       5 mean      
14 Drinking Water                Aesthetic Objective                     1       1 max       
15 Recreation                    Primary Contact                         1       1 max       
16 Drinking Water                Maximum Acceptable Concentration       30       5 quantile90
17 Recreation                    Aesthetic Objective                    30       5 mean      
18 Aquatic Life - Estuarine      Short-term acute                        1       1 max       
19 Aquatic Life - Estuarine      Long-term chronic                      30       5 mean      
20 Aquatic Life - Freshwater     Short-term acute                        1       1 min       
21 Recreation                    Primary Contact - Single Sample Max     1       1 max       
22 Recreation                    Primary Contact - Geometric Mean       30       5 geomean   
23 Wildlife - Dietary            Long-term chronic                      30       5 mean      
24 Aquatic Life - Freshwater     Long-term chronic                      30       5 median    
25 Wildlife                      Long-term chronic                      30       5 median    
26 Recreation                    Primary Contact                         1       1 min       
27 Wildlife - Dietary Freshwater Short-term acute                        1       1 max       
28 Wildlife - Dietary Marine     Short-term acute                        1       1 max       
29 Drinking Water                Narrative                               1       1 max       
30 Recreation                    Aesthetic Objective                     1       1 max   
```

**Comment by joethorley** [comment]
In my opinion the Type column is a mix of Use, Days, Samples and Statistics.

I think all the types other than Long-term chronic and Short-term acute should move into the use column so that they are separated from the Use by a '-' and the Type column should vanish with the short-term or long term status in the shiny app being determined from the number of days.

Thoughts @atillmanns and @HeatherGranger?

**Comment by HeatherGranger** [comment]
The Type column is a mix of Use, Days, Samples and Stats in the english sense, but in the guideline world, the Types listed do describe what 'Type' the guideline is. I'd prefer to keep 'Drinking Water' and 'Recreation' as the Use. Adding the extra details isn't pertaining to the regular language we use to describe the Drinking Water and Recreation use. 

If the Statistic column is remaining, then having the extra single sample max and geometric mean details could be removed.

**Comment by sebdalgarno** [comment]
@HeatherGranger the Single Sample Max and Geometric Mean were added so that the user of the app did not need to see or deal with Statistic...i.e. every other case in the spreadsheet does not need to be distinguished by Statistic.

**Comment by joethorley** [comment]
OK we'll leave as is.
