### ISSUE TITLE
Change Use to Value

### ISSUE THREAD

**Issue by sebdalgarno** [bcgov/wqg_data#53]
as column name

**Comment by sebdalgarno** [comment]
I can implement but can you confirm this is what you want @atillmanns ?

**Comment by atillmanns** [comment]
@sebdalgarno - yes please.  I know we discussed this for the wqg_all spreadsheet as well.  I think it's fine if the spreadsheet remains as "Uses".  The audiences for these two tools are different.  It's important that we highlight the fact that we have many values when it comes to managing water quality.
