### ISSUE TITLE
Hardness Total and Hardness Dissolved

### ISSUE THREAD

**Issue by sebdalgarno** [bcgov/wqg_data#54]
In cases where it doesn't make a difference if user provides Hardness Total or Hardness Dissolved, we should just include Hardness Total in the Conditions. 

this will be a more robust solution than trying to hack around it in the app.

**Comment by atillmanns** [comment]
@sebdalgarno - when calculating the WQG, the user may use dissolved or total hardness.  For the WQG user interface, it's not really a concern.  We just need one box for hardness.  For the WQG analysis app, the user may need to pull either total or dissolved hardness from EMS so the app needs to allow them to do both.

**Comment by sebdalgarno** [comment]
OK thanks for clarification! I will leave as is in the spreadsheet and work around it in the WQG user interface.
 I'll close this now because there is a similar issue open in the shinywqg repository: https://github.com/poissonconsulting/shinywqg/issues/29
