### ISSUE TITLE
What does 'Based on screening level concentration' mean?

### ISSUE THREAD

**Issue by joethorley** [bcgov/wqg_data#55]
Is there any information in 'Based on screening level concentration mean' or can it be dropped from Notes?

**Comment by atillmanns** [comment]
Screening level concentration is one way that sediment quality guidelines can be derived.  Not all methods are the same so it may be helpful for people to know the method that was used.  Please keep this.

**Comment by joethorley** [comment]
@atillmanns - do you want it appearing in the Notes section for the shiny app? - otherwise we could move it to a MethodsNotes section.

**Comment by atillmanns** [comment]
@joethorley - I'm not sure the difference between a notes section and a methods notes section?

**Comment by joethorley** [comment]
see for methods notes section https://github.com/bcgov/wqg_data/issues/67
