### ISSUE TITLE
Is 'Severe Effects Level' different to Probable Effect?

### ISSUE THREAD

**Issue by joethorley** [bcgov/wqg_data#56]
ie should PredictedEffectLevel be changed from Probable Effect to Severe Effect?

**Comment by atillmanns** [comment]
I could find only two uses of the word "severe" in the spreadsheet.  I removed it Aldrin (row #50) as it should remain as probable effect.  But for PAH (#699), this should remain in the notes

**Comment by joethorley** [comment]
Moved into limit notes for PAH.
