### ISSUE TITLE
Is 'Must be calculated using BLM software' informative?

### ISSUE THREAD

**Issue by joethorley** [bcgov/wqg_data#59]

**Comment by atillmanns** [comment]
The users should know that we do have AL WQGs for copper but they are not accessible in the spreadsheet.  This is the lookup table we hope to add to the app next year.

**Comment by joethorley** [comment]
Can we move these two Notes to the LimitsNotes and change to something more informative?

**Comment by joethorley** [comment]
Edited and moved to LimitNotes for copper.
