### ISSUE TITLE
Why is 'Reported as mg/L NO3-N (nitrate-N)' only reported for two values of Nitrate Total?

### ISSUE THREAD

**Issue by joethorley** [bcgov/wqg_data#62]
Does it add anything?

**Comment by joethorley** [comment]
same as 'Reported as mg/L NO2-N (nitrite-N)' for Nitrite Total.

**Comment by HeatherGranger** [comment]
the guideline for drinking water and recreation are reported as the nitrogen portion of nitrate, and the nitrite. The other guidelines I believe are just reported as nitrate. As the drinking water and recreation guidelines are largely adopted from Health Canada, they sometimes are presented in different ways than the BC developed aquatic life guidelines.

**Comment by joethorley** [comment]
Thanks @HeatherGranger
