### ISSUE TITLE
Notes refer to median but statistic refers to mean for Organic Carbon Dissolved

### ISSUE THREAD

**Issue by joethorley** [bcgov/wqg_data#63]
Notes say 

"Long-term median within 20% of background median and the 30-day median for both DOC and TOC is within 20% of seasonally-adjusted median background levels as measured histroically or at appropriate reference sites.  The 30-day median calculation should be based on a minimum of 5 weekly samples taken over a period of 30 days."

but statistic is mean.

Which is correct?

**Comment by atillmanns** [comment]
Median is correct.  Corrected.
