### ISSUE TITLE
Benzo(g,h,i)perylene duplicates

### ISSUE THREAD

**Issue by sebdalgarno** [bcgov/wqg_data#64]
Benzo(g,h,i)perylene; Aquatic Life - Freshwater; Sediment; Long-term chronic; No Effect;
same Limits but only slightly different notes saying the same thing: 1. Based on screening level concentration and 2. effect levels based on screening level concentration

Benzo(g,h,i)perylene; Aquatic Life - Freshwater; Sediment; Long-term chronic; Probable Effect;
Slightly different limits (0.321 vs. 3.21 must be data entry error?) and slightly different notes saying the same thing: 1. Based on screening level concentration and 2. effect levels based on screening level concentration

**Comment by atillmanns** [comment]
@sebdalgarno - agreed there are two entries.  UniqueID 121 & 122 is basically a repeat of UniqueID 119 & 120 and can be deleted.

**Comment by sebdalgarno** [comment]
OK great I'll delete those. Just to confirm, is 0.321 (0r 3.21) the correct value for "Probable Effect"?

**Comment by sebdalgarno** [comment]
@atillmanns is taking care of this

**Comment by atillmanns** [comment]
Done.
