### ISSUE TITLE
Notes say 'screening level concentration 10th percentile' but statistic is max?

### ISSUE THREAD

**Issue by joethorley** [bcgov/wqg_data#65]
Polychlorinated Biphenyls Arochlor 1016 notes are 

'screening level concentration 10th percentile' 

and also

'screening level concentration 90th percentile'

but statistics are max - which is correct?

**Comment by atillmanns** [comment]
The notes are referring to how the guideline was derived not how the guideline should be used, so they are both correct.

**Comment by joethorley** [comment]
Should 'screening level concentration 10th percentile' be edited to 'Effect level based on 10th percentile screening level concentration.'?

**Comment by atillmanns** [comment]
Yes please.  Good catch.
