### ISSUE TITLE
Can 'LOCATION_PURPOSE = River, stream or creek' be reduced to 'River, stream or creek'?

### ISSUE THREAD

**Issue by joethorley** [bcgov/wqg_data#66]

**Comment by atillmanns** [comment]
@HeatherGranger - what do you think?  The only entry like this is for Chlorophyll a for recreation.  Is it useful to have it entered in a way that is consistent with the EMS coding?

**Comment by HeatherGranger** [comment]
@joethorley Yes. I originally wrote it like that to communicate that this guideline only pertain to that column of data in EMS. Location_Purpose is a column in EMS. I don't believe there's a code for Location_Purpose in EMS, just the words.
