### ISSUE TITLE
Statistic is differentiating guidelines - geomean

### ISSUE THREAD

**Issue by sebdalgarno** [bcgov/wqg_data#68]
See UniqueID 385/386 and 388/389
Statistic (geomean vs. mean) appears to be the only thing differentiating Guidelines (considering Variable, Use, Media, Type, PredictedEffectLevel, Direction).

It can be differentiated by Days/Samples but the app currently does not allow user to filter by Days/Samples.

If we want to remove Statistic from user selection in App, do we need to adjust the Type of these to differentiate them? (e.g. 'Primary Contact - long-term' for the geomean)

thoughts @atillmanns ?

**Comment by sebdalgarno** [comment]
this could also be resolved by e.g. adding 'geomean' and 'mean' to each respective LimitNotes

**Comment by sebdalgarno** [comment]
FYI I've confirmed that these are the only remaining cases where Statistic is the only thing differentiating the Limits

**Comment by atillmanns** [comment]
For 385/386, there are two limits, one for max and one for geomean, so need both.  The same is for 388/389.  @sebdalgarno does this make sense or maybe I'm missing something?

**Comment by HeatherGranger** [comment]
Agree with angeline. If statistic column is removed, then type could be updated to Primary Contact - Single Sample Max and Primary Contact - Geometric Mean

**Comment by sebdalgarno** [comment]
yes I agree for sure that both limits should remain. Also to be clear, I'm not suggesting that we remove Statistic column from spreadsheet. It's just that if we want to remove Statistic from user filter options and report display in the Shiny app then we need some way to inform the user why they are getting two different limits...perhaps in these cases we could add the statistic to the LimitNotes

**Comment by joethorley** [comment]
I think it makes more sense to code as Primary Contact - Short-term acute and Primary Contact - Long-term chronic. Thoughts?

**Comment by HeatherGranger** [comment]
Either adding to the LimitNotes or updating the Type makes sense to me. The wording for Recreation guidelines are based on human health, not aquatic life terminology, so short term acute and long term chronic are not correct. The wording here is what they're called in the guideline document:
 Primary Contact - Single Sample Max and Primary Contact - Geometric Mean

**Comment by joethorley** [comment]
OK lets go with the guideline terminology.

**Comment by sebdalgarno** [comment]
OK great I'll make those changes
