### ISSUE TITLE
Is there any point having 'Further guidelines for total suspended solids is available in the overview and technical reports.'

### ISSUE THREAD

**Issue by joethorley** [bcgov/wqg_data#73]
This occurs for Turbidity but isn't it implicit.

**Comment by atillmanns** [comment]
The guideline information has only been entered for turbidity NTU but there is another narrative guideline written for suspended solids.  I didn't think it was necessary to include both but the user needs to know that if they are looking for the suspended solid guideline to click on the overview or technical report.
