### ISSUE TITLE
Replace '80% white light' for Colour Apparent

### ISSUE THREAD

**Issue by joethorley** [bcgov/wqg_data#74]
With 

`EMS_0001 * 0.8`

for the limit?

**Comment by sebdalgarno** [comment]
yes I think this would be a good change

Currently a special case to deal with limit of 80% since it is neither an expression or a number.

**Comment by atillmanns** [comment]
How will this show up in the WQG user app?  Will it be translated to 80% white light?

**Comment by joethorley** [comment]
Currently 
The user would be asked for the Colour Apparent and the limit would appear as 80% of whatever value the user provided.

Alternatively
We could make the app translate limits that have say EMS_Code * 0.8 into "80% of background".

If the bit about white light has special meaning we could have "white light" in the LimitsNotes.

**Comment by atillmanns** [comment]
The alternative please, with "white light" in LimitsNotes.
