### ISSUE TITLE
What is the alternative to 'Reported as mg/L NO3-N (nitrate-N)'?

### ISSUE THREAD

**Issue by joethorley** [bcgov/wqg_data#75]

**Comment by atillmanns** [comment]
@HeatherGranger - suggestions?

**Comment by joethorley** [comment]
Just to clarify I mean what is the N03-N being reported in contrast to?

**Comment by HeatherGranger** [comment]
I don't quite understand. The nitrate guideline for drinking water has two guideline values: 45 mg/L nitrate and 10 mg/L NO3-N (this is the nitrogen component of the nitrate). The nitrite guideline also has two guideline values. @joethorley are you looking for another way of writing the nitrate-N unit?

**Comment by joethorley** [comment]
Thanks @HeatherGranger. 
I'm just trying to understand.
Based on what you've said I'm thinking it makes sense to set the component to be `Total - Nitrogen` for those where we are dealing with NO3-N.
Thoughts?

**Comment by HeatherGranger** [comment]
Ya this is a tricky one for machine readability. The guideline is represented as the total nitrogen component of nitrate. There isn't an equivalent variable in EMS that matches with that; it's a one-off. If we say Total - Nitrogen, then were not specifically referring to the nitrate portion.

**Comment by joethorley** [comment]
I think we are because the Variable name is still Nitrate.

**Comment by atillmanns** [comment]
I went back and looked at the technical documents. The aquatic life guidelines are all reported as mg/L N, (same as NO3-N), so I will change the units to mg/L N for those guidelines that are reported in nitrogen and leave it as mg/L for the recreation and drinking water guidelines that report as nitrate.  Sound good @HeatherGranger ?  (Note: the conversion factor is: nitrate multiplied by 0.2258 equals nitrate as N)

**Comment by atillmanns** [comment]
Changed all the units and took the notes out of the limit notes so this should be easier for machines and people.
