### ISSUE TITLE
For salinity replace 'Change in concentration of +/- 10% NaCl or equivalent' with equation

### ISSUE THREAD

**Issue by joethorley** [bcgov/wqg_data#76]
In particular it corresponds to two levels with

Lower: EMS_0130 * 0.9
Upper: EMS_0130 * 1.1

Thoughts?

**Comment by atillmanns** [comment]
When the guidelines are expressed as changes over background, I think the user needs to know this as it provides information about the sensitivity of the system to change.  How about we put in the equation for the limit, but write out the narrative WQG in the condition notes.  Then the user can both calculate the guideline if they have the data but also get the message that the system is sensitive to change.

**Comment by joethorley** [comment]
I think this is a good solution and ties in with #74
