### ISSUE TITLE
Limits should not be based on statistical significant change...

### ISSUE THREAD

**Issue by joethorley** [bcgov/wqg_data#80]
See for example

> No statistically significant decrease in pH from background.  No restriction on the increase in pH except in boggy areas that have a unique fauna or flora.  Site-specific ambient water quality objectives to restrict the pH increase in areas with a unique fauna and flora are recommended.

The problem is that statistical significance depends on both sample and effect size (as well as method) so that if enough data is collected all effect sizes will eventually become significant. Conversely if very little data is collected no effect sizes will be significant.

**Comment by atillmanns** [comment]
You have a point but I cannot change the text of the WQG.  This is a policy document and cannot be easily changed.
