### ISSUE TITLE
EMS code convention

### ISSUE THREAD

**Issue by sebdalgarno** [bcgov/wqg_data#82]
In the wqbc::limits and wqbc::codes table, the convention for an EMS code consisting of EMS_ followed by two letters is "EMS_X__X". However in the new guidelines the convention is "EMS_X_-X" (with hyphen instead of underscore)

The cases include:
- Boron Total (EMS_B_-T) 
- Uranium Total (EMS_U_-T)
- Phosphorous Total (EMS_P_-T)

Is there a reason for the switch?

**Comment by joethorley** [comment]
No this is an error (I guess using sub instead of sub) they should all be _.

**Comment by sebdalgarno** [comment]
OK great - should I make that change on wqg_data now?

**Comment by joethorley** [comment]
Yes please

**Comment by sebdalgarno** [comment]
done - note it also affected Vanadium Total
