### ISSUE TITLE
old wqbc::limits table vs. new wqbc limits table

### ISSUE THREAD

**Issue by sebdalgarno** [bcgov/wqg_data#83]
I need to recreate the wqbc::limits table from the new guidelines spreadsheet for the ShinyRems app and for use in wqbc. The wqbc::limits table has the following columns: Variable, Use (all 'Freshwater Life'), Term, Condition, UpperLimit, and Units.

I have filtered out any limits from the new guidelines spreadsheet with Use of 'Freshwater Life' (e.g. 'Aquatic Life - Freshwater') and Media of "Water" and Direction of "Upper Limit". I have recreated the Term column where Days/Samples of 1 is "short" and Days/Samples of 30/5 is "long". 

I think the table should have all of the records from the old limits table (for backward compatibility) as well as any new limits that are Freshwater Life (Use) and Water (Media) and Upper Limit (Direction). It is fine for the limits to have new Conditions or UpperLimits, but they should have the same EMS_Code and Term.

I will add the issues I have come across in the comments below and number them so we can easily reference them:

**Comment by sebdalgarno** [comment]
**1.** The following limits have different values for Term column:
- EMS_AS_T - term is ‘Long’ in old table but ‘Short’ in new table
- EMS_CLO3 - term is “Short” in old table but “Long’ in new table
- EMS_MTBE - term is “Long’ in old table but “Short” in new table

**Comment by sebdalgarno** [comment]
**2.** There is no Chloride Total (EMS_0104) in new guidelines (only Chloride Dissolved (EMS_1104)

**Comment by sebdalgarno** [comment]
**3.** There is 'Chlorine Residual: Total' (EMS_1016) in wqbc limits and 'Chlorine Total' (EMS_CL2_) in new guidelines...however there is no EMS_1016 in new guidelines or EMS_CL2_ in wqbc limits

**Comment by sebdalgarno** [comment]
**4.** The following are in the wqbc limits but missing from new guidelines:
- Nitrogen Dissolved (EMS_1114)
- Nitrogen Total (EMS_0114)
- Phosphorous Dissolved (EMS_P__D)

**Comment by sebdalgarno** [comment]
**5.** Copper Total (EMS_CU_T) is in wqbc limits but in new guidelines sheet it has Media of "Sediment"  - it appears to be the only guideline with Media 'Sediment' that also exists in the wqbc limits table. Is this a mistake? Should there also be a Media = 'Water' limit for Copper Total?

**Comment by sebdalgarno** [comment]
**6.** Copper Total (EMS_CU_T) - in wqbc limits table there are limits for Copper Total with Term = "Long". In the new guidelines there are no limits for Copper Total - Aquatic Life Freshwater with Term = "Long"

**Comment by atillmanns** [comment]
Note: some sediment samples have a Days/Samples of 1 but they have a term of "long" so the rule quoted below won't work for sediments.

> I have filtered out any limits from the new guidelines spreadsheet with Use of 'Freshwater Life' (e.g. 'Aquatic Life - Freshwater') and Media of "Water" and Direction of "Upper Limit". I have recreated the Term column where Days/Samples of 1 is "short" and Days/Samples of 30/5 is "long".

**Comment by atillmanns** [comment]
1. I have double checked these and the new table is correct.
EMS_AS_T - term is ‘Long’ in old table but ‘Short’ in new table - **the new table is correct**
EMS_CLO3 - term is “Short” in old table but “Long’ in new table - **the new table is correct**
EMS_MTBE - term is “Long’ in old table but “Short” in new table - **the new table is correct**

**Comment by sebdalgarno** [comment]
> Note: some sediment samples have a Days/Samples of 1 but they have a term of "long" so the rule quoted below won't work for sediments.
> 
> > I have filtered out any limits from the new guidelines spreadsheet with Use of 'Freshwater Life' (e.g. 'Aquatic Life - Freshwater') and Media of "Water" and Direction of "Upper Limit". I have recreated the Term column where Days/Samples of 1 is "short" and Days/Samples of 30/5 is "long".

OK great - I will assume the Copper Total Term is short then since that is what it is in wqbc limits

**Comment by sebdalgarno** [comment]
the above comments resolve issues 1 and 6

**Comment by atillmanns** [comment]
2 - chloride can only be dissolved, it is an ion.  So new table is correct.

**Comment by atillmanns** [comment]
3 - should be Chlorine Residual: Total' (EMS_1016) - corrected in spreadsheet

**Comment by atillmanns** [comment]
4. 
Nitrogen Dissolved (EMS_1114) -  there is no freshwater - AL WQG for nitrogen dissolved
Nitrogen Total (EMS_0114) -  there is no freshwater - AL WQG for nitrogen total
- the only nitrogen guidelines are for nitrate, nitrite and ammonia

Phosphorous Dissolved (EMS_P__D) - there is no freshwater AL - WQG for dissolved phosphorus

**Comment by sebdalgarno** [comment]
> Nitrogen Dissolved (EMS_1114) - there is no freshwater - AL WQG for nitrogen dissolved
> Nitrogen Total (EMS_0114) - there is no freshwater - AL WQG for nitrogen total
> 
> * the only nitrogen guidelines are for nitrate, nitrite and ammonia
> 
> Phosphorous Dissolved (EMS_P__D) - there is no freshwater AL - WQG for dissolved phosphorus

Thanks for confirmation - they will not appear in the new wqbc limits table

**Comment by atillmanns** [comment]
5. The freshwater AL WQG was updated earlier this year.  There is no longer a freshwater AL WQG for total copper, it is now just for dissolved copper and it needs to be calculated using the BLM software.  The WQGs for other values should be the same.

**Comment by sebdalgarno** [comment]
> 1. The freshwater AL WQG was updated earlier this year.  There is no longer a freshwater AL WQG for total copper, it is now just for dissolved copper and it needs to be calculated using the BLM software.  The WQGs for other values should be the same.

OK thanks - Copper Total will not appear in the new wqbc limits table

**Comment by sebdalgarno** [comment]
From slack - final issue resolved

<img width="663" alt="Screen Shot 2020-03-17 at 10 46 15 AM" src="https://user-images.githubusercontent.com/15878432/76885511-94ae5180-683c-11ea-8474-d9f516d28815.png">
