### ISSUE TITLE
Units discrepancy wqbc limits vs new guidelines

### ISSUE THREAD

**Issue by sebdalgarno** [bcgov/wqg_data#84]
Three Variables have different units in the new guidelines
- Ammonia Total has unit 'mg/L N' in new guidelines vs. 'mg/L' in wqbc limits
- Barium Total has unit 'mg/L' in new guidelines vs. 'ug/L' in wqbc limits
- Nitrate Total has unit 'mg/L N' in new guidelines vs. 'mg/L' in wqbc limits

**Comment by joethorley** [comment]
I think we should move the N from Units to the Component column as `mg/L N` is not a recognized unit but we should confirm with @atillmanns and @HeatherGranger

**Comment by HeatherGranger** [comment]
I can answer for nitrate - I think this could work. What do you think @atillmanns

**Comment by atillmanns** [comment]
Right - I suppose throwing the "N" in the units column will prevent the ability to easily convert between units.  The phrases, "Total" and "Dissolved" have typically been used to refer to whether or not the substance was found in a whole water sample or whether or not it had been filtered first.  This is the way we define it in our technical documents so I don't want to confuse people by adding other information in this column.  I think it makes most sense to add something to the limit notes.  We could add back in, "reported as N" to the limit notes.

**Comment by joethorley** [comment]
I fear it will get lost in the limit notes and will be hard for a machine to parse.

One option is to separate it from Total and Dissolved using a - ie Dissolved - Nitrogen.

Another option is to add a column called Subcomponent and have it in here?

**Comment by sebdalgarno** [comment]
"reported as N" makes sense I think. In fact some already have this in the ConditionNotes:

<img width="830" alt="Screen Shot 2020-03-18 at 8 32 32 AM" src="https://user-images.githubusercontent.com/15878432/76977861-24163c00-68f3-11ea-97d4-9969d51d4910.png">

If we are to move to LimitNotes, then we should move these ConditionNotes to the LimitNotes as well I think

**Comment by atillmanns** [comment]
I don't understand why we need a whole new column?  Why cannot this information be included in the limit notes?

**Comment by HeatherGranger** [comment]
I think adding 'reported as N' makes sense in the LimitNotes best I think. The unit is more specific to the LimitNotes rather than the ConditionNotes. I don't think adding another column would necessarily clarify things for a user.

**Comment by sebdalgarno** [comment]
OK I will add 'reported as N' to LimitNotes and move from ConditionNotes to LimitNotes where present

**Comment by atillmanns** [comment]
@sebdalgarno - thanks!  And for barium, mg/L is correct.

**Comment by sebdalgarno** [comment]
done
