### ISSUE TITLE
Variables missing EMS_Code

### ISSUE THREAD

**Issue by sebdalgarno** [bcgov/wqg_data#85]
there are 31 cases of Variables without EMS_Code
Should these eventually be filled in?

**Comment by atillmanns** [comment]
There are no EMS codes for these variables.  I imagine that means they cannot be used in the water quality analysis app, but they are still included in wqg_all spreadsheet because they can be included (and need to be included) in the ShinyWQG.

**Comment by sebdalgarno** [comment]
OK sounds good - they'll be removed from the wqbc limits table
