### ISSUE TITLE
EMS_M050 duplicates

### ISSUE THREAD

**Issue by sebdalgarno** [bcgov/wqg_data#86]
<img width="1232" alt="Screen Shot 2020-03-17 at 6 05 10 PM" src="https://user-images.githubusercontent.com/15878432/76915256-f50fb400-6879-11ea-8ae2-4b504438767c.png">

These all have the same EMS code but different Variable names and different Limits (unrelated to Condition)

**Comment by atillmanns** [comment]
Yes, that's the only code we have for monochlorophenols so these are not really duplicates.  It is a code that applies to a group of substances.

**Comment by joethorley** [comment]
I think we should either 
1) remove the EMS_Code because other than the limits (and variable names which are not reliable to tell things apart) they are confusing duplicates. 
2) Distinguish them in a Subcomponent column (see #84) or in the LimitsNotes

**Comment by atillmanns** [comment]
I don't agree that these are confusing duplicates.  The variables are all monochlorophenols (EMS_M050) and the variable allows them to be distinguished as it clearly states the location of the chlorine atom.  Agreed that ideally there would be a unique EMS code for each monochlorophenol, but this is not the case in EMS.  The user of the water quality analysis app will have to know which monochlorophenol they are dealing with but if the data is stored in EMS, it will be stored under this code.

**Comment by sebdalgarno** [comment]
OK we will leave this - they will all be removed from wqbc limits table
