### ISSUE TITLE
Lead Total limit R expression

### ISSUE THREAD

**Issue by sebdalgarno** [bcgov/wqg_data#87]
This cannot be evaluated:
"exp(1.273 * LN(EMS_0107) - 4.704) + 3.31"

**Comment by sebdalgarno** [comment]
and others with LN in it

**Comment by sebdalgarno** [comment]
related to https://github.com/poissonconsulting/shinywqg/issues/44

**Comment by sebdalgarno** [comment]
I can switch LN to log

**Comment by joethorley** [comment]
Yes that should be log.

**Comment by sebdalgarno** [comment]
great Iv'e made that change
